### ISSUE TITLE
真的超级喜欢霞鹜漫黑这款马克笔字体，求恢复更新维护！

### ISSUE THREAD

**Issue by jaytai** [lxgw/LxgwMarkerGothic#3]
经常使用，还是会是不是碰到缺字的情况，有点可惜，期待作者在工作和维护霞鹜文楷之余，如果可能的话，能恢复对霞鹜漫黑字体的更新维护，让这款好字体能达到较为完整的状态。

**Comment by lxgw** [comment]
您好像已经提了一个 issue，不是吗？ #2

**Comment by jaytai** [comment]
> 您好像已经提了一个 issue，不是吗？ #2

抱歉，我关掉另一个了。经常来看，可能这个字体项目关注的人少？平时做视频的时候很喜欢用这个字体，经常缺字，看上去有点别扭，现在暂时用霞鹜文楷替代，还是非常期待能用回霞鹜漫黑。
谢谢作者

**Comment by shmilybaozi** [comment]
我也很喜欢的！如果能更新的话就太好了

**Comment by lxgw** [comment]
目前还有 379 字补完 GB/T 2312。补完后该字体将支持 GB/T 2312 所收汉字及通用规范汉字表前两级汉字。现关闭该 issue。
